local_repository(
    name = "emsdk",
    path = "..",
)

load("@rules_emscripten//:deps.bzl", "deps")

deps()

load("@rules_emscripten//:emscripten_deps.bzl", "emscripten_deps")

emscripten_deps()

load("@rules_emscripten//:toolchains.bzl", "register_emscripten_toolchains")

register_emscripten_toolchains(cache = {
    "configuration": ["--lto"],
    "targets": [
        "crtbegin",
        "libprintf_long_double-debug",
        "libstubs-debug",
        "libnoexit",
        "libc-debug",
        "libdlmalloc",
        "libcompiler_rt",
        "libc++-noexcept",
        "libc++abi-debug-noexcept",
        "libsockets"
    ]
})
